name: blossomcompanion
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_rust_bridge: ^2.5.0
  http: ^1.1.0
  intl: ^0.19.0
  metadata_god: ^1.0.0
  on_audio_query: ^2.9.0
  path_provider: ^2.1.4
  permission_handler: ^11.3.1
  url_launcher: ^6.3.1

  path: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
